### ISSUE TITLE
TypeError: Cannot read property 'launchBrowser' of undefined

### ISSUE THREAD

**Issue by luckylooke** [kossnocorp/on-build-webpack#2]
I am getting error:
```
TypeError: Cannot read property 'launchBrowser' of undefined
    at onReady (/Users/user/project/node_modules/@ionic/app-scripts/dist/serve.js:70:15)
    at /Users/user/project/client/node_modules/@ionic/app-scripts/dist/serve.js:63:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
trying basic example
with webpack 3.7.1

**Comment by luckylooke** [comment]
seems to be not related to this plugin, sorry

**Comment by luckylooke** [comment]
I have found real cause of problem here: https://forum.ionicframework.com/t/typeerror-cannot-read-property-launchbrowser-of-undefined/100975/7
